import oracledb
import numpy as np
import ollama

# Oracle connection details
DB_USER = "raguser"
DB_PASSWORD = "ragpwd"
DB_DSN = "localhost:1521/FREEPDB1"

conn = oracledb.connect(
    user=DB_USER,
    password=DB_PASSWORD,
    dsn=DB_DSN
)

cursor = conn.cursor()
print("Connected to Oracle 23ai")


cursor.execute("""
CREATE TABLE doc_chunks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    content CLOB,
    embedding VECTOR(768)
)
""")

cursor.execute("""
CREATE VECTOR INDEX doc_vec_idx
ON doc_chunks(embedding)
WITH DISTANCE COSINE
""")

conn.commit()

def embed_text(text):
    response = ollama.embeddings(
        model="nomic-embed-text",
        prompt=text
    )
    return np.array(response["embedding"], dtype=np.float32)

documents = [
    "Oracle 23ai supports native vector search using SQL.",
    "Vector search enables semantic similarity for RAG pipelines.",
    "Ollama can run LLMs and embedding models locally.",
    "RAG combines retrieval with LLM generation for accurate answers."
]

for doc in documents:
    vec = embed_text(doc).tolist()
    cursor.execute(
        "INSERT INTO doc_chunks (content, embedding) VALUES (:1, :2)",
        [doc, vec]
    )

conn.commit()
print("Documents inserted")


query = "What is vector search used for?"
results = retrieve_context(query)

for text, dist in results:
    print(f"Distance: {dist:.3f} | {text}")

def build_prompt(contexts, question):
    context_text = "\n".join([c[0] for c in contexts])

    return f"""
You are an AI assistant.
Answer the question using ONLY the context below.
If not found, say "I don't know".

Context:
{context_text}

Question:
{question}
"""

def generate_answer(prompt):
    response = ollama.chat(
        model="llama3",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    return response["message"]["content"]

question = "Explain Oracle 23ai vector search"

contexts = retrieve_context(question)
prompt = build_prompt(contexts, question)

answer = generate_answer(prompt)
print(answer)

cursor.close()
conn.close()
